export const categories = ["Abusive relationships > Check partner's history of abuse",
    "Abusive relationships > Domestic abuse support(general)",
    "Abusive relationships > Female Genital Mutilation(FGM)",
    "Abusive relationships > Healing after an abusive relationship",
    "Abusive relationships > Honour based and family abuse",
    "Abusive relationships > Is this abuse ?",
    "Abusive relationships > Online or digital abuse",
    "Abusive relationships > Report domestic abuse",
    "Abusive relationships > Safety in abusive relationships",
    "Abusive relationships > Support for abusers to stop",
    "Accidents and injuries > Bites and stings > Animal and human bites",
    "Accidents and injuries > Bites and stings > Insect bites and stings",
    "Accidents and injuries > Burns and scalds > Acid and chemical burns",
    "Accidents and injuries > Burns and scalds > Sunburn",
    "Accidents and injuries > Accident prevention > Baby safety",
    "Accidents and injuries > Accident prevention > Child safety",
    "Accidents and injuries > Accident prevention > Elder safety",
    "Accidents and injuries > Accident prevention > Safety out and about",
    "Accidents and injuries > Burns and scalds > Burns and scalds(general)",
    "Accidents and injuries > Cuts and grazes",
    "Accidents and injuries > Head injuries",
    "Adoption and foster care > Support for those adopted > Tracking your genetic family",
    "Adoption and foster care > Having your child in care > Putting your child into care",
    "Adoption and foster care > Having your child in care > Getting child back from care",
    "Adoption and foster care > Having your child in care > Child taken into care",
    "Adoption and foster care > Putting a child up for adoption > Having your child adopted",
    "Adoption and foster care > Putting a child up for adoption > Reconnect with adopted child",
    "Adoption and foster care > Support for those adopted > Finding out you are adopted",
    "Adoption and foster care > Support for care leavers",
    "Allergies > Allergy testing",
    "Allergies > Food allergies",
    "Allergies > Pet allergies",
    "Allergies > Hay fever",
    "Allergies > Severe allergies",
    "Allergies > Skin allergies",
    "Allergies > Allergies(general)",
    "Animal welfare > Puppy farms",
    "Animal welfare > Report a breeder",
    "Animal welfare > Animal neglect",
    "Animal welfare > Dangerous animal",
    "Baby loss > Ectopic pregnancy",
    "Baby loss > Baby funerals and memorials",
    "Baby loss > Miscarriage",
    "Baby loss > Molar pregnancy",
    "Baby loss > Stillbirth",
    "Baby loss > Baby loss support",
    "Baby loss > Cot death(SIDS)",
    "Benefits and tax credits > Tax credits > Child tax credit resources",
    "Benefits and tax credits > Tax credits > Tax credits calculator",
    "Benefits and tax credits > Tax credits > Understanding tax credits",
    "Benefits and tax credits > Tax credits > Working tax credits",
    "Benefits and tax credits > Benefit fraud",
    "Benefits and tax credits > Benefit overpayments",
    "Benefits and tax credits > Benefit sanctions",
    "Benefits and tax credits > Benefits calculator",
    "Benefits and tax credits > Challenge a benefit decision",
    "Benefits and tax credits > Child benefit",
    "Benefits and tax credits > Benefits / tax credits complaints",
    "Benefits and tax credits > Universal credit",
    "Benefits and tax credits > Benefits injured at work",
    "Benefits and tax credits > Benefits for carers",
    "Benefits and tax credits > Disability benefits",
    "Body confidence > Body Dysmorphic Disorder(BDD)",
    "Body confidence > Feeling body confident",
    "Boredom > Learning something new",
    "    Boredom > Things to do",
    "Borrowing money > Borrowing options",
    "Borrowing money > Borrow from friends or family",
    "Borrowing money > Lend to friends and family",
    "Borrowing money > Warning: Pay day lenders",
    "Brain, nerves and spinal cord > Brain injury > Brain stem death",
    "Brain, nerves and spinal cord > Brain injury > Coma",
    "Brain, nerves and spinal cord > Brain injury > Brain injury support",
    "Brain, nerves and spinal cord > Chronic conditions > Multiple sclerosis(MS)",
    "Brain, nerves and spinal cord > Chronic conditions > CFS / ME",
    "Brain, nerves and spinal cord > Chronic conditions > Motor neurone disease(MND)",
    "Brain, nerves and spinal cord > Chronic conditions > Parkinson's disease",
    "Brain, nerves and spinal cord > Chronic conditions > Spinal muscular atrophy(SMA)",
    "Brain, nerves and spinal cord > Chronic conditions > Muscular dystrophy",
    "Brain, nerves and spinal cord > Dementia and Alzheimer's  >  Alzheimer's disease",
    "Brain, nerves and spinal cord > Dementia and Alzheimer's  >  Dementia with Lewy bodies",
    "Brain, nerves and spinal cord > Dementia and Alzheimer's  >  Frontotemporal dementia",
    "Brain, nerves and spinal cord > Dementia and Alzheimer's  >  Caring for someone with dementia",
    "Brain, nerves and spinal cord > Dementia and Alzheimer's  >  Vascular dementia",
    "Brain, nerves and spinal cord > Dementia and Alzheimer's  >  Young onset dementia",
    "Brain, nerves and spinal cord > Dementia and Alzheimer's  >  Dementia and Alzheimers (general)",
    "Brain, nerves and spinal cord > Dementia and Alzheimer's  >  Dementia",
    "Brain, nerves and spinal cord > Headaches and migraines > Headaches",
    "Brain, nerves and spinal cord > Headaches and migraines > Migraines",
    "Brain, nerves and spinal cord > Asperger Syndrome(AS)",
    "Brain, nerves and spinal cord > Autism(ASD)",
    "Brain, nerves and spinal cord > Epilepsy",
    "Brain, nerves and spinal cord > Fibromyalgia syndrome(FMS)",
    "Brain, nerves and spinal cord > Huntington's disease",
    "Brain, nerves and spinal cord > Rare brain disorders",
    "Brain, nerves and spinal cord > Spinal cord injury(SDI)",
    "Brain, nerves and spinal cord > Stroke",
    "Brain, nerves and spinal cord > Transient ischaemic attack(TIA)",
    "Brain, nerves and spinal cord > Facial nerve pain",
    "Brain, nerves and spinal cord > Facial nerve pain",
    "Brain, nerves and spinal cord > Memory problems",
    "Brain, nerves and spinal cord > Tuberous sclerosis",
    "Brain, nerves and spinal cord > Spina bifida",
    "Brain, nerves and spinal cord > Intracranial Hypertension(IH)",
    "Brain, nerves and spinal cord > Meningitis",
    "Brain, nerves and spinal cord > Facial palsy",
    "Breaking up > Children and separation > Ex won't let you see the kids",
    "Breaking up > Children and separation > Child arrangements",
    "Breaking up > Children and separation > Children's feelings if separating",
    "Breaking up > Children and separation > Telling your kids about divorce",
    "Breaking up > End a marriage or partnership > DIY divorce",
    "Breaking up > End a marriage or partnership > Ending a civil partnership",
    "Breaking up > End a marriage or partnership > Ending a marriage",
    "Breaking up > End a marriage or partnership > Find a divorce lawyer",
    "Breaking up > End a marriage or partnership > Managed divorce services",
    "Breaking up > End a marriage or partnership > Religious divorce",
    "Breaking up > End a marriage or partnership > Solicitor managed divorce services",
    "Breaking up > End a marriage or partnership > Divorce visa implications",
    "Breaking up > End a marriage or partnership > Coping with divorce or separation",
    "Breaking up > Ending a relationship > Splitting up",
    "Breaking up > Ending a relationship > Considering splitting up",
    "Breaking up > Sorting housing matters > Separation housing rights(married)",
    "Breaking up > Sorting housing matters > Separation housing rights(not married)",
    "Breaking up > Sorting housing matters > Separation housing rights(married)",
    "Breaking up > Sorting housing matters > Separation housing rights(not married)",
    "Breaking up > Money and break-ups > Money matters if divorcing",
    "Breaking up > Money and break-ups > Money matters if separating",
    "Breaking up > Coping after break-up",
    "Breaking up > Break - ups and pets",
    "Breaking up > Relationship mediation services",
    "Cancer > Blood cancer > Acute myeloid leukaemia(AML)",
    "Cancer > Blood cancer > Chronic lymphocytic leukaemia(CLL)",
    "Cancer > Blood cancer > Chronic myeloid leukaemia(CML)",
    "Cancer > Blood cancer > Hairy cell leukaemia",
    "Cancer > Blood cancer > Myeloma",
    "Cancer > Blood cancer > Other blood cancers",
    "Cancer > Blood cancer > Lymphoma",
    "Cancer > Brain tumours > Acoustic neuroma",
    "Cancer > Brain tumours > Astrocytoma and glioblastoma(GBM)",
    "Cancer > Brain tumours > Craniopharyngioma",
    "Cancer > Brain tumours > Embryonal tumours",
    "Cancer > Brain tumours > Ependymoma",
    "Cancer > Brain tumours > Glioma",
    "Cancer > Brain tumours > Hemangioblastoma",
    "Cancer > Brain tumours > Lymphoma of brain or spinal cord",
    "Cancer > Brain tumours > Meningioma",
    "Cancer > Brain tumours > Oligodendroglioma",
    "Cancer > Brain tumours > Other brain tumour",
    "Cancer > Brain tumours > Pineal region tumours",
    "Cancer > Brain tumours > Pituitary tumours",
    "Cancer > Brain tumours > Spinal cord tumours",
    "Cancer > Cancer support(general) > Chemotherapy",
    "Cancer > Cancer support(general) > Diagnosed with cancer",
    "Cancer > Cancer support(general) > Life after cancer",
    "Cancer > Cancer support(general) > Support someone with cancer",
    "Cancer > Cancer support(general) > Terminal cancer",
    "Cancer > Cancer support(general) > Cancer support organisations",
    "Cancer > Head and neck cancer > Laryngeal cancer",
    "Cancer > Head and neck cancer > Mouth and oropharyngeal cancer",
    "Cancer > Head and neck cancer > Nasopharyngeal cancer",
    "Cancer > Head and neck cancer > Oesophageal cancer",
    "Cancer > Head and neck cancer > Salivary gland cancer",
    "Cancer > Head and neck cancer > Throat cancer",
    "Cancer > Head and neck cancer > Tongue cancer",
    "Cancer > Head and neck cancer > Tonsil cancer",
    "Cancer > Kidney cancer > Other kidney cancer",
    "Cancer > Kidney cancer > Renal cell cancer",
    "Cancer > Men's cancer  >  Penile",
    "Cancer > Men's cancer  >  Prostate",
    "Cancer > Men's cancer  >  Testicular",
    "Cancer > Rare cancers > Acute lymphoblastic leukaemia(ALL)",
    "Cancer > Rare cancers > Adrenal gland tumours",
    "Cancer > Rare cancers > Bile duct cancer",
    "Cancer > Rare cancers > Cancer of unknown primary(CUP)",
    "Cancer > Rare cancers > Ear cancer",
    "Cancer > Rare cancers > Gallbladder cancer",
    "Cancer > Rare cancers > Mesothelioma",
    "Cancer > Rare cancers > Myosarcoma",
    "Cancer > Rare cancers > Nasal and sinus cancer",
    "Cancer > Rare cancers > Neuroendocrine tumours and carcinoid syndrome",
    "Cancer > Rare cancers > Other rare cancers",
    "Cancer > Rare cancers > Pseudomyxoma peritonei(PMP)",
    "Cancer > Rare cancers > Thymomas and thymus gland tumours",
    "Cancer > Rare cancers > Thyroid cancer",
    "Cancer > Sarcomas > Bone sarcoma",
    "Cancer > Sarcomas > Gastrointestinal stromal tumours(GIST)",
    "Cancer > Sarcomas > Gynaecological sarcoma",
    "Cancer > Sarcomas > Retroperitoneal sarcoma",
    "Cancer > Sarcomas > Soft tissue sarcoma",
    "Cancer > Skin cancer > Basal Cell Carcinoma(BCC)",
    "Cancer > Skin cancer > Melanoma skin cancer",
    "Cancer > Skin cancer > Other skin cancers",
    "Cancer > Skin cancer > Squamous cell skin cancer(SCC)",
    "Cancer > Stomach(gastric) cancers > Anal cancer",
    "Cancer > Stomach(gastric) cancers > Gastro oesophageal junction cancers",
    "Cancer > Stomach(gastric) cancers > Large bowel(colon or rectum) cancer",
    "Cancer > Stomach(gastric) cancers > Linitis plastica of the stomach",
    "Cancer > Stomach(gastric) cancers > Liver cancer",
    "Cancer > Stomach(gastric) cancers > Pancreatic cancer",
    "Cancer > Stomach(gastric) cancers > Rectal cancer",
    "Cancer > Stomach(gastric) cancers > Small bowel cancer",
    "Cancer > Stomach(gastric) cancers > Stomach(gastric) cancer",
    "Cancer > Stomach(gastric) cancers > Stomach neuroendocrine tumours(NETs)",
    "Cancer > Women's cancer  >  Cervical cancer",
    "Cancer > Women's cancer  >  Gestational trophoblastic disease (GTD)",
    "Cancer > Women's cancer  >  Ovarian cancer",
    "Cancer > Women's cancer  >  Placenta cancer",
    "Cancer > Women's cancer  >  Vaginal cancer",
    "Cancer > Women's cancer  >  Vulval",
    "Cancer > Women's cancer  >  Womb cancer",
    "Cancer > Bladder cancer",
    "Cancer > Bone cancer",
    "Cancer > Breast cancer",
    "Cancer > Lung cancer",
    "Caring and care services > Care homes > Care home complaints",
    "Caring and care services > Care homes > Find a nursing home",
    "Caring and care services > Care homes > Find a residential home",
    "Caring and care services > Care homes > Help to pay for care homes",
    "Caring and care services > Care homes > Care homes information",
    "Caring and care services > Care workers > Care worker complaints",
    "Caring and care services > Care workers > Help to pay for care costs",
    "Caring and care services > Care workers > Hire a care worker",
    "Caring and care services > Care workers > Care services information",
    "Caring and care services > Hospices > Finding a hospice",
    "Caring and care services > Hospices > Information about hospices",
    "Caring and care services > Care for loved ones at home",
    "Caring and care services > Find a nursing home",
    "Caring and care services > Find and arrange social care",
    "Caring and care services > Home adaptations",
    "Caring and care services > Home care services",
    "Caring and care services > Power of Attorney problems",
    "Caring and care services > Respite care(breaks)",
    "Caring and care services > Specialist housing for older people",
    "Caring and care services > Understanding care options",
    "Caring and care services > Home care gadgets and equipment",
    "Caring and care services > Help to pay for home adaptations",
    "Child education > Picking subjects",
    "Child education > Private tutors",
    "Child education > School complaints",
    "Child education > School options",
    "Child education > SEND resources",
    "Child education > Education support(5 - 12 years)",
    "Child education > Education support(13 - 18 years)",
    "Child loss > Child funerals and memorials",
    "Child loss > Loss of a child by suicide",
    "Child loss > Adult child loss",
    "Child loss > Child loss support",
    "Childcare > Au Pair",
    "Childcare > Babysitters",
    "Childcare > Childcare complaints",
    "Childcare > Childminders",
    "Childcare > Day nurseries",
    "Childcare > Nannies",
    "Childcare > Playgroups",
    "Childcare > Sure Start Children's Centres",
    "Childcare > Virtual nannies",
    "Childcare > Childcare information",
    "Children with additional needs > Children with Asperger Syndrome",
    "Children with additional needs > Children with Autism",
    "Children with additional needs > Blind or visually impaired children",
    "Children with additional needs > Children with Deafness",
    "Children with additional needs > Children with disabilities(general)",
    "Children with additional needs > Deaf or hard of hearing children",
    "Children with learning disabilities > Children with learning disabilities(general)",
    "Children with learning disabilities > Children with Cerebral palsy",
    "Children with learning disabilities > Children with Down's syndrome",
    "Children with learning disabilities > Children with Fragile X syndrome",
    "Children with learning disabilities > Children with GDD",
    "Children with learning disabilities > Children with PMLD",
    "Children with learning disabilities > Children with Williams syndrome",
    "Children's health  >  Allergies in children",
    "Children's health  >  Asthma in children",
    "Children's health  >  Cancer in children",
    "Children's health  >  Children's dental care",
    "Children's health  >  Children with epilepsy",
    "Children's health  >  Functional abdominal pain",
    "Children's health  >  Help for parents of sick kids",
    "Children's health  >  Infections in children",
    "Children's health  >  Children's vaccinations",
    "Children's health  >  Children's heart conditions",
    "Children's health  >  Diabetes in children",
    "Complimentary therapies > Acupuncture or acupressure",
    "Complimentary therapies > Alexander Technique",
    "Complimentary therapies > Aromatherapy",
    "Complimentary therapies > Herbal medicines",
    "Complimentary therapies > Homeopathy",
    "Complimentary therapies > Hypnotherapy",
    "Complimentary therapies > Massage therapy",
    "Complimentary therapies > Naturopathy",
    "Complimentary therapies > Osteopathy or chiropractic",
    "Complimentary therapies > Physiotherapy",
    "Complimentary therapies > Reflexology",
    "Complimentary therapies > Reiki or energy therapies",
    "Complimentary therapies > Shiatsu",
    "Coronavirus and money > Coronavirus and benefits",
    "Coronavirus and money > Emergency financial aid",
    "Crime support > Child abuse > Police check someone for child safety",
    "Crime support > Child abuse > Historic abuse support",
    "Crime support > Child abuse > Report child abuse suspicions",
    "Crime support > Child abuse > Child abuse support for families",
    "Crime support > Child abuse > Child abuse support",
    "Crime support > Child abuse > Young victims of crime",
    "Crime support > Collisions and road traffic accidents > Report dangerous driving",
    "Crime support > Collisions and road traffic accidents > Road accident support",
    "Crime support > Cyber crime > Cyber crime support",
    "Crime support > Cyber crime > Hacking",
    "Crime support > Cyber crime > Online bullying or trolling",
    "Crime support > Cyber crime > Online stalking",
    "Crime support > Cyber crime > Reporting cyber crimes",
    "Crime support > Cyber crime > Revenge porn",
    "Crime support > Cyber crime > Webcam blackmail",
    "Crime support > Cyber crime > Staying safe online",
    "Crime support > Cyber crime > Online scams and fraud",
    "Crime support > Exploitation and blackmail > Blackmail",
    "Crime support > Exploitation and blackmail > Report exploitation or blackmail",
    "Crime support > Exploitation and blackmail > Sexual exploitation",
    "Crime support > Gang crime > Gang crime or violence support",
    "Crime support > Gang crime > Pressured to join a gang",
    "Crime support > Gang crime > Report gang crime",
    "Crime support > Gang crime > Ex - gang member support",
    "Crime support > Gang crime > Support to leave a gang",
    "Crime support > Hate crimes and discrimination > Discrimination: alternative subcultures",
    "Crime support > Hate crimes and discrimination > Disability discrimination",
    "Crime support > Hate crimes and discrimination > Gender identity discrimination",
    "Crime support > Hate crimes and discrimination > Race or ethnicity discrimination",
    "Crime support > Hate crimes and discrimination > Religious discrimination",
    "Crime support > Hate crimes and discrimination > Sexual orientation discrimination",
    "Crime support > Hate crimes and discrimination > Report hate crime",
    "Crime support > Hate crimes and discrimination > Hate crime support(general)",
    "Crime support > Kidnapping or child abductions > Parental child abduction",
    "Crime support > Kidnapping or child abductions > Report kidnapping or abduction",
    "Crime support > Kidnapping or child abductions > Hostage and kidnap survivor support",
    "Crime support > Kidnapping or child abductions > Kidnap / abduction support for families",
    "Crime support > Modern slavery > Forced labour and slavery",
    "Crime support > Modern slavery > Human trafficking",
    "Crime support > Modern slavery > Report slavery concerns",
    "Crime support > Rape and sexual crimes > Drink spiking",
    "Crime support > Rape and sexual crimes > Rape or sexual assault",
    "Crime support > Rape and sexual crimes > Upskirting",
    "Crime support > Scams and fraud > Counterfeit or pirated goods",
    "Crime support > Scams and fraud > Doorstep scams or fraud",
    "Crime support > Scams and fraud > Financial scams or fraud",
    "Crime support > Scams and fraud > Identity theft ?",
    "    Crime support > Scams and fraud > Phone scams or cold calls",
    "Crime support > Scams and fraud > Postal scams",
    "Crime support > Stalking > Record stalking incidents",
    "Crime support > Stalking > Stalking in the workplace",
    "Crime support > Stalking > Harassment or stalking support",
    "Crime support > Terrorism or extremism > Terrorism victims: Immediate support",
    "Crime support > Terrorism or extremism > Terrorism victims: Ongoing support",
    "Crime support > Terrorism or extremism > Online radicalisation",
    "Crime support > Terrorism or extremism > Report terrorism suspicions",
    "Crime support > Theft, robbery and burglary > Burglary",
    "Crime support > Theft, robbery and burglary > Recovering stolen items",
    "Crime support > Theft, robbery and burglary > Report a theft, robbery or burglary",
    "Crime support > Theft, robbery and burglary > Robbery",
    "Crime support > Theft, robbery and burglary > Stolen car",
    "Crime support > Theft, robbery and burglary > Theft",
    "Crime support > Violent crime > Acid attacks",
    "Crime support > Violent crime > Assault",
    "Crime support > Violent crime > Gang violence",
    "Crime support > Violent crime > Gun and knife crime",
    "Crime support > Report vandals or antisocial behaviour",
    "Crime support > UK victims of crime abroad",
    "Crime support > Prostitution",
    "Dating > Online dating > Dating sites and apps",
    "Dating > Online dating > Dating online safety advice",
    "Dating > Dating advice",
    "Dating > Dating agencies",
    "Dental and oral health > Broken or knocked out tooth",
    "Dental and oral health > Dental care",
    "Dental and oral health > Dental implants and bridges",
    "Dental and oral health > Emergency dental care",
    "Dental and oral health > Gum disease",
    "Dental and oral health > Teeth straightening",
    "Dental and oral health > Tooth decay",
    "Diabetes > Diabetic retinopathy",
    "Diabetes > Diabetes support(general)",
    "Diabetes > Gestational diabetes",
    "Diabetes > Latent Autoimmune Diabetes(LADA)",
    "Diabetes > Maturity onset diabetes(MODY)",
    "Diabetes > Neonatal diabetes",
    "Diabetes > Type 1 diabetes",
    "Diabetes > Type 2 diabetes",
    "Diabetes > Type 3c diabetes",
    "Diabetes > Wolfram Syndrome",
    "Digestive system and liver > Appendix > Appendicitis",
    "Digestive system and liver > Bowel health > Faecal(bowel) incontinence",
    "Digestive system and liver > Bowel health > Irritable Bowel Syndrome(IBS)",
    "Digestive system and liver > Bowel health > Polyps in the bowel",
    "Digestive system and liver > Common digestive problems > Constipation",
    "Digestive system and liver > Common digestive problems > Diarrhoea",
    "Digestive system and liver > Common digestive problems > Flatulence",
    "Digestive system and liver > Common digestive problems > Haemorrhoids(piles)",
    "Digestive system and liver > Common digestive problems > Vomiting",
    "Digestive system and liver > Digestive and gut health > Achalasia",
    "Digestive system and liver > Digestive and gut health > Adhesions",
    "Digestive system and liver > Digestive and gut health > Ascites",
    "Digestive system and liver > Digestive and gut health > Barrett's Oesophagus",
    "Digestive system and liver > Digestive and gut health > Eosinophilic diseases",
    "Digestive system and liver > Digestive and gut health > Digestive and gut health(general)",
    "Digestive system and liver > Digestive and gut health > Stoma",
    "Digestive system and liver > Gallbladder > Acute cholecystitis",
    "Digestive system and liver > Gallbladder > Biliary sphincter disorders",
    "Digestive system and liver > Gallbladder > Gallstones",
    "Digestive system and liver > Gastric surgery > Dumping syndrome",
    "Digestive system and liver > Gastric surgery > Gastric bypass surgery",
    "Digestive system and liver > Intestine conditions > Chronic intestinal pseudo - obstruction",
    "Digestive system and liver > Intestine conditions > Coeliac disease",
    "Digestive system and liver > Intestine conditions > Crohn's disease",
    "Digestive system and liver > Intestine conditions > Diverticular disease",
    "Digestive system and liver > Intestine conditions > Microscopic colitis",
    "Digestive system and liver > Intestine conditions > Perianal disease",
    "Digestive system and liver > Intestine conditions > Ulcerative colitis",
    "Digestive system and liver > Liver health > Alcohol - related liver disease(ARLD)",
    "Digestive system and liver > Liver health > Cirrhosis",
    "Digestive system and liver > Liver health > Liver disease",
    "Digestive system and liver > Pancreatic health > Acute pancreatitis",
    "Digestive system and liver > Pancreatic health > Chronic pancreatitis",
    "Digestive system and liver > Pancreatic health > Pancreatic exocrine insufficiency(PEI)",
    "Digestive system and liver > Stomach health > Gastro - oesophageal reflux disease(GORD)",
    "Digestive system and liver > Stomach health > Gastroenteritis",
    "Digestive system and liver > Stomach health > Non - ulcer(or functional) dyspepsia",
    "Digestive system and liver > Stomach health > Stomach ulcers",
    "Digestive system and liver > Pelvic radiation disease",
    "Digestive system and liver > Spleen problems and removal",
    "Digestive system and liver > Swallowing problems(dysphagia)",
    "Direction and self - improvement > Find direction and purpose",
    "Direction and self - improvement > Self - improvement resources",
    "Ears and hearing > Hearing loss",
    "Ears and hearing > Labyrinthitis",
    "Ears and hearing > Meniere's disease",
    "Ears and hearing > Outer ear infections",
    "Ears and hearing > Sound sensitivities",
    "Ears and hearing > Tinnitus",
    "Ears and hearing > Vertigo",
    "Ears and hearing > Hearing services",
    "Ears and hearing > Vestibular(inner ear) disorders",
    "Eyes and vision > Eye cancer",
    "Eyes and vision > Eye tests",
    "Eyes and vision > Glaucoma",
    "Eyes and vision > Laser eye surgery",
    "Eyes and vision > Lazy eye",
    "Eyes and vision > Other eye issues",
    "Eyes and vision > Blindness or sight loss",
    "Family arguments > Resolve a family argument",
    "Family arguments > Family mediation",
    "Family arguments > Family law services",
    "Family arguments > Family therapy",
    "Family money matters > Help with child - related costs > Free school meals",
    "Family money matters > Help with child - related costs > Healthy Start vouchers",
    "Family money matters > Help with child - related costs > Help with childcare costs",
    "Family money matters > Help with child - related costs > Help with school clothing",
    "Family money matters > Help with child - related costs > Help with school transport",
    "Family money matters > Help with child - related costs > Maternity grant",
    "Family money matters > Family budgets",
    "Family money matters > Financial support for parents",
    "Family money matters > Teaching kids about money",
    "Family money matters > Will and inheritance disputes",
    "Find a job and career advice > Career skills and training > Search career courses or training",
    "Find a job and career advice > Career skills and training > Skills health check",
    "Find a job and career advice > Find a job > Find a graduate job",
    "Find a job and career advice > Find a job > Find an apprenticeship",
    "Find a job and career advice > Find a job > Find job vacancies",
    "Find a job and career advice > Find a job > Recruitment agencies",
    "Find a job and career advice > Find a mentor or career coach > Find a career coach",
    "Find a job and career advice > Find a mentor or career coach > Find a mentor",
    "Find a job and career advice > Help to apply for a job > CV templates and examples",
    "Find a job and career advice > Help to apply for a job > CV writing services",
    "Find a job and career advice > Help to apply for a job > Help reviewing your CV",
    "Find a job and career advice > Help to apply for a job > Job application forms",
    "Find a job and career advice > Help to apply for a job > Cover letters",
    "Find a job and career advice > Interview support > Interview advice for disabled people",
    "Find a job and career advice > Interview support > Common interview questions",
    "Find a job and career advice > Interview support > Help to buy interview clothes",
    "Find a job and career advice > Interview support > Mock interview practice",
    "Find a job and career advice > Changing career",
    "Find a job and career advice > Find a volunteering opportunity",
    "Find a job and career advice > Career advice",
    "Friends > Bullying help for adults",
    "Friends > Making friends",
    "Friends > Making friends in later years",
    "Friends > Find mum friends",
    "Gender and sexuality > LGBT + support",
    "Gender and sexuality > LGBT + support for families",
    "Gender and sexuality > Gender dysphoria and gender identity",
    "Getting a pet > Finding a pet right for you",
    "Getting a pet > Therapy or assistance pets",
    "Health and care services > Cosmetic surgery issues",
    "Health and care services > Dental care complaints",
    "Health and care services > Donors and recipients",
    "Health and care services > Find NHS services",
    "Health and care services > Health advice in other languages",
    "Health and care services > Help in hospital",
    "Health and care services > Medical care complaints",
    "Health and care services > Prescription services",
    "Health and care services > Social care complaints",
    "Health and care services > Travel to healthcare",
    "Health and care services > Other medical services",
    "Health and care services > Undiagnosed conditions",
    "Health and care services > First aid",
    "Health and care services > Help after leaving hospital",
    "Healthy living > Nutrition and diet > Healthy eating recipes and tips",
    "Healthy living > Nutrition and diet > Meal planning on a budget",
    "Healthy living > Nutrition and diet > Weight management",
    "Healthy living > Nutrition and diet > Nutritionist or dietician",
    "Healthy living > Drinking habits",
    "Healthy living > Quit smoking",
    "Healthy living > Fitness and exercise",
    "Heart, blood and circulation > Blood > Anaemia",
    "Heart, blood and circulation > Blood > Cervical artery dissection",
    "Heart, blood and circulation > Blood > Deep vein thrombosis(DVT)",
    "Heart, blood and circulation > Blood > High blood pressure(hypertension)",
    "Heart, blood and circulation > Blood > High cholesterol",
    "Heart, blood and circulation > Blood > Hyperglycaemia(high blood sugar)",
    "Heart, blood and circulation > Blood > Hypoglycaemia(low blood sugar)",
    "Heart, blood and circulation > Blood > Low blood pressure(hypotension)",
    "Heart, blood and circulation > Blood > Sepsis",
    "Heart, blood and circulation > Blood > Septic shock",
    "Heart, blood and circulation > Blood > Sickle cell disease",
    "Heart, blood and circulation > Blood > Porphyria",
    "Heart, blood and circulation > Circulation > Lymphoedema",
    "Heart, blood and circulation > Circulation > Overactive thyroid(hyperthyroidism)",
    "Heart, blood and circulation > Circulation > Peripheral arterial disease",
    "Heart, blood and circulation > Circulation > Raynaud's phenomenon",
    "Heart, blood and circulation > Circulation > Thoracic aortic aneurysm",
    "Heart, blood and circulation > Circulation > Underactive thyroid(hypothyroidism)",
    "Heart, blood and circulation > Circulation > Varicose veins",
    "Heart, blood and circulation > Circulation > Postural tachycardia syndrome",
    "Heart, blood and circulation > Heart > Angina",
    "Heart, blood and circulation > Heart > Arrhythmia(irregular heart rhythm)",
    "Heart, blood and circulation > Heart > Coronary heart disease",
    "Heart, blood and circulation > Heart > Heart failure",
    "Heart, blood and circulation > Heart > Heart valve disease",
    "Heart, blood and circulation > Heart > Cardiomyopathy",
    "Heart, blood and circulation > Heart > Single ventricle heart condition",
    "Heart, blood and circulation > Heart > Heart health",
    "Heart, blood and circulation > Heart > Sudden adult death syndrome(SADS)",
    "Help a child facing issues > Child being bullied",
    "Help a child facing issues > Exam stress",
    "Help a child facing issues > Heartbreak in young people",
    "Help a child facing issues > Child joining a gang concerns",
    "Help a child facing issues > Online grooming",
    "Help a child facing issues > Puberty and adolescence",
    "Help a child facing issues > Teenage pregnancy",
    "Help a child facing issues > My child is drinking",
    "Help a child facing issues > My child is smoking",
    "Help a child facing issues > My child is taking drugs",
    "Help to buy the essentials > Furniture and whitegoods > Find discounted goods",
    "Help to buy the essentials > Furniture and whitegoods > Free or low cost furniture",
    "Help to buy the essentials > Help with clothing costs > Help pay for interview clothes",
    "Help to buy the essentials > Help with clothing costs > Help with school clothes",
    "Help to buy the essentials > Help with food costs",
    "Help with healthcare costs > Free or low cost healthcare items",
    "Help with healthcare costs > Help with healthcare travel costs",
    "Help with healthcare costs > Help with prescription costs",
    "Help with home costs and bills > Help with bills > Cold weather payments",
    "Help with home costs and bills > Help with bills > Council tax reduction",
    "Help with home costs and bills > Help with bills > Gas and electric bills",
    "Help with home costs and bills > Help with bills > Other help to pay for bills",
    "Help with home costs and bills > Help with bills > Phone and broadband",
    "Help with home costs and bills > Help with bills > Water bills",
    "Help with home costs and bills > Help with rent > Challenging a rent increase",
    "Help with home costs and bills > Help with rent > Deposit and upfront costs",
    "Help with home costs and bills > Help with rent > Discretionary housing payments",
    "Help with home costs and bills > Help with rent > Help with Housing Benefits",
    "Help with home costs and bills > Help with rent > Rent arrears",
    "Help with home costs and bills > Help with rent > Struggling to pay rent",
    "Help with home costs and bills > Help for homeowners",
    "Home support services > Assisted garden maintenance",
    "Home support services > Mobile meals",
    "Homelessness support > Emergency housing and homeless hostels",
    "Homelessness support > Other homelessness support",
    "House fires > Cladding and fire safety",
    "House fires > Fire safety in the home",
    "House fires > Support after a fire",
    "Insurance > Disputing an insurance claim",
    "Insurance > Making an insurance claim",
    "Insurance > Problems getting insurance",
    "Isolation > Befriending networks",
    "Isolation > Combatting loneliness",
    "Isolation > Holidays for solo travellers",
    "Learning difficulties > Dyslexia",
    "Learning difficulties > Dyspraxia",
    "Learning disabilities > Down's syndrome",
    "Learning disabilities > Fragile X syndrome",
    "Learning disabilities > Global Development Delay",
    "Learning disabilities > Adults with PMLD",
    "Learning disabilities > Williams syndrome",
    "Learning disabilities > Learning disability support(general)",
    "Learning disabilities > Foetal alcohol spectrum disorders(FASD)",
    "Legal services > Free or low cost legal support",
    "Living environment > Neighbours > Get to know your neighbours",
    "Living environment > Neighbours > Resolve neighbour disputes",
    "Living environment > Neighbourhood problems",
    "Living environment > Home safey and security",
    "Loss of a loved one > Financial support after loss",
    "Loss of a loved one > Funeral and memorials",
    "Loss of a loved one > If someone has died abroad",
    "Loss of a loved one > Loss by suicide",
    "Loss of a loved one > Bereavement support",
    "Loss of a loved one > Murder or manslaughter",
    "Loss of a loved one > Unexpected loss",
    "Loss of a loved one > What to do when someone dies",
    "Loss of a loved one > Loss of your partner",
    "Lost, stolen or stray pets > Lost pet",
    "Lost, stolen or stray pets > Stolen pet",
    "Lungs and breathing > Asbestosis",
    "Lungs and breathing > Asthma",
    "Lungs and breathing > Bronchiectasis",
    "Lungs and breathing > COPD",
    "Lungs and breathing > Coughing",
    "Lungs and breathing > Cystic fibrosis",
    "Lungs and breathing > Idiopathic pulmonary fibrosis(IPF)",
    "Lungs and breathing > Legionnaires' disease",
    "Lungs and breathing > Other lung diseases",
    "Lungs and breathing > Pneumonia",
    "Lungs and breathing > Dyspnoea(breathing difficulties)",
    "Marriage > Forced marriage",
    "Marriage > Marriage doubts",
    "Marriage > Wedding planning support",
    "Men's health  >  Benign prostate enlargement",
    "Men's health  >  Male puberty",
    "Men's health  >  Testicular lumps or swelling",
    "Men's health  >  Vasectomy",
    "Men's health  >  Vasectomy reversal",
    "Men's health  >  Klinefelter syndrome",
    "Mental health > Addiction and recovery > Gambling addiction",
    "Mental health > Addiction and recovery > Alcohol addiction",
    "Mental health > Addiction and recovery > Cocaine addiction",
    "Mental health > Addiction and recovery > Heroin addiction",
    "Mental health > Addiction and recovery > Internet addiction",
    "Mental health > Addiction and recovery > Marijuana addiction",
    "Mental health > Addiction and recovery > Painkillers addiction",
    "Mental health > Addiction and recovery > Sex and porn addiction",
    "Mental health > Addiction and recovery > Shopping addiction",
    "Mental health > Addiction and recovery > Solvents addiction",
    "Mental health > Addiction and recovery > Workaholic",
    "Mental health > Anxiety, panic and phobias > Generalised Anxiety Disorder(GAD)",
    "Mental health > Anxiety, panic and phobias > Panic Disorder and attacks",
    "Mental health > Anxiety, panic and phobias > Phobias",
    "Mental health > Anxiety, panic and phobias > Social Anxiety Disorder",
    "Mental health > Children's mental health  >  ADHD in children",
    "Mental health > Children's mental health  >  Angry children",
    "Mental health > Children's mental health  >  Anxious children",
    "Mental health > Children's mental health  >  Behavioural problems",
    "Mental health > Children's mental health  >  Child mental health resources",
    "Mental health > Children's mental health  >  Conduct disorder",
    "Mental health > Children's mental health  >  Depression in children",
    "Mental health > Children's mental health  >  Eating disorders in children",
    "Mental health > Children's mental health  >  OCD in children",
    "Mental health > Children's mental health  >  Self-esteem in children",
    "Mental health > Children's mental health  >  Self-harm in children",
    "Mental health > Children's mental health  >  Trauma and PTSD in children",
    "Mental health > Depression > Persistent depressive disorder(dysthymia)",
    "Mental health > Depression > Seasonal Affective Disorder(SAD)",
    "Mental health > Depression > Major depressive disorder(MDD)",
    "Mental health > Depression > Depression(general support)",
    "Mental health > Eating disorders > Anorexia",
    "Mental health > Eating disorders > Avoidant or restrictive food intake",
    "Mental health > Eating disorders > Binge eating disorder",
    "Mental health > Eating disorders > Bulimia",
    "Mental health > Eating disorders > Eating disorders(general)",
    "Mental health > Emotional wellbeing > Feeling angry",
    "Mental health > Emotional wellbeing > Feeling anxious",
    "Mental health > Emotional wellbeing > Feeling isolated",
    "Mental health > Emotional wellbeing > Feeling stressed",
    "Mental health > Emotional wellbeing > Hearing voices",
    "Mental health > Emotional wellbeing > Mindfulness",
    "Mental health > Emotional wellbeing > Paranoia",
    "Mental health > Emotional wellbeing > Self - esteem",
    "Mental health > Emotional wellbeing > Worrying",
    "Mental health > Emotional wellbeing > Emotional wellbeing(general)",
    "Mental health > Maternal mental health > Antenatal depression(before birth)",
    "Mental health > Maternal mental health > Broad support resources",
    "Mental health > Maternal mental health > Perinatal anxiety",
    "Mental health > Maternal mental health > Perinatal depression",
    "Mental health > Maternal mental health > Perinatal OCD",
    "Mental health > Maternal mental health > Postnatal depression(after birth)",
    "Mental health > Maternal mental health > Postpartum psychosis(after birth)",
    "Mental health > Maternal mental health > PTSD and birth trauma",
    "Mental health > Mental health care > Advance statements and decisions",
    "Mental health > Mental health care > Residential care",
    "Mental health > Mental health care > Sectioning and welfare rights",
    "Mental health > Mental health care > Social care",
    "Mental health > Money and mental health > Help managing money",
    "Mental health > Money and mental health > Welfare and benefits",
    "Mental health > Personality disorders > Antisocial personality disorder",
    "Mental health > Personality disorders > Avoidant personality disorder",
    "Mental health > Personality disorders > Borderline personality disorder",
    "Mental health > Personality disorders > Dependent personality disorder",
    "Mental health > Personality disorders > Histrionic personality disorder",
    "Mental health > Personality disorders > Narcissistic personality disorder",
    "Mental health > Personality disorders > Obsessive - compulsive personality disorder",
    "Mental health > Personality disorders > Paranoid personality disorder",
    "Mental health > Personality disorders > Personality disorders(general)",
    "Mental health > Personality disorders > Schizoid personality disorder",
    "Mental health > Personality disorders > Schizotypal personality disorder",
    "Mental health > Psychosis and schizophrenia > Paraphrenia",
    "Mental health > Psychosis and schizophrenia > Psychosis",
    "Mental health > Psychosis and schizophrenia > Schizoaffective Disorder",
    "Mental health > Psychosis and schizophrenia > Schizophrenia",
    "Mental health > Suicide > After an attempt",
    "Mental health > Suicide > Suicidal feelings",
    "Mental health > Suicide > Support someone suicidal",
    "Mental health > Suicide > Suicide prevention",
    "Mental health > Trauma and PTSD > Complex PTSD",
    "Mental health > Trauma and PTSD > Post - traumatic stress disorder(PTSD)",
    "Mental health > Trauma and PTSD > Trauma",
    "Mental health > Women's mental health  >  Womens mental health (general)",
    "Mental health > Women's mental health  >  Menopausal mental health",
    "Mental health > Bipolar Disorder",
    "Mental health > Hoarding",
    "Mental health > Men's mental health",
    "Mental health > Mental health and work",
    "Mental health > Munchausen's syndrome",
    "Mental health > OCD Obsessive Compulsive Disorder",
    "Mental health > Self - harm",
    "Mental health > Mental health resources(general)",
    "Mental health > Counselling and talking therapies",
    "Mental health > ADHD in adults",
    "Mental health > Dissociation",
    "Mental health > Support someone's mental health",
    "Missing person > People missing abroad",
    "Missing person > Support for a missing person",
    "Missing person > Missing people support",
    "Money advice > Find a financial advisor",
    "Money advice > Free financial advice",
    "Money in relationships > Separation and money matters > Divorcing and finances",
    "Money in relationships > Separation and money matters > Separation and finances",
    "Money in relationships > Dealing with joint debts",
    "Money in relationships > Financial planning in relationships",
    "Money in relationships > Lying about money and spending",
    "Money in relationships > Prenups and postnups",
    "Money in relationships > Talking about money in relationships",
    "Money management > Arranging Power of Attorney",
    "Money management > Donating money",
    "Money management > Ways to earn extra cash",
    "Money management > Will writing",
    "Money management > Help with budgeting",
    "Money management > Credit report and scores",
    "Money worries > Bankruptcy",
    "Money worries > Debt advice",
    "Money worries > Support someone with money problems",
    "Money worries > Problems opening bank accounts",
    "Money worries > Spending problems",
    "Money worries > Worried about money issues",
    "Muscles, bones and joints > Arthritis and related conditions > Ankylosing spondylitis",
    "Muscles, bones and joints > Arthritis and related conditions > Arthritis",
    "Muscles, bones and joints > Arthritis and related conditions > Cervical spondylosis",
    "Muscles, bones and joints > Arthritis and related conditions > Enteropathic arthritis",
    "Muscles, bones and joints > Arthritis and related conditions > Fibromyalgia",
    "Muscles, bones and joints > Arthritis and related conditions > Gout",
    "Muscles, bones and joints > Arthritis and related conditions > Lupus",
    "Muscles, bones and joints > Arthritis and related conditions > Osteoarthritis",
    "Muscles, bones and joints > Arthritis and related conditions > Polymyalgia rheumatica(PMR)",
    "Muscles, bones and joints > Arthritis and related conditions > Psoriatic arthritis",
    "Muscles, bones and joints > Arthritis and related conditions > Reactive arthritis",
    "Muscles, bones and joints > Arthritis and related conditions > Rheumatoid arthritis",
    "Muscles, bones and joints > Arthritis and related conditions > Axial Spondyloarthritis",
    "Muscles, bones and joints > Arthritis and related conditions > Juvenile Idiopathic Arthritis",
    "Muscles, bones and joints > Bone conditions > Brittle bone disease",
    "Muscles, bones and joints > Bone conditions > Osteopenia",
    "Muscles, bones and joints > Bone conditions > Osteoporosis",
    "Muscles, bones and joints > Bone conditions > Paget's disease of bone",
    "Muscles, bones and joints > Hip problems > Hip replacement",
    "Muscles, bones and joints > Hip problems > Other hip problems",
    "Muscles, bones and joints > Muscle, bone or joint injury > Repetitive strain injury(RSI)",
    "Muscles, bones and joints > Muscle, bone or joint injury > Sports injuries",
    "Muscles, bones and joints > Leg, knee and foot > Ankle problems",
    "Muscles, bones and joints > Leg, knee and foot > Calf problems",
    "Muscles, bones and joints > Leg, knee and foot > Foot problems",
    "Muscles, bones and joints > Leg, knee and foot > Knee problems",
    "Muscles, bones and joints > Leg, knee and foot > Thigh problems",
    "Muscles, bones and joints > Movement disorders > Ataxia",
    "Muscles, bones and joints > Movement disorders > Dystonia",
    "Muscles, bones and joints > Movement disorders > Gait disorders",
    "Muscles, bones and joints > Movement disorders > Parkinson's tremors",
    "Muscles, bones and joints > Movement disorders > Restless legs syndrome",
    "Muscles, bones and joints > Movement disorders > Spasticity",
    "Muscles, bones and joints > Movement disorders > Stiff person syndrome",
    "Muscles, bones and joints > Movement disorders > Tics and Tourette syndrome",
    "Muscles, bones and joints > Movement disorders > Tremors or shaking hands",
    "Muscles, bones and joints > Shoulder and neck > Frozen shoulder",
    "Muscles, bones and joints > Shoulder and neck > Neck problems",
    "Muscles, bones and joints > Shoulder and neck > Other shoulder problems",
    "Muscles, bones and joints > Wrist, hand and finger problems > Carpal tunnel syndrome",
    "Muscles, bones and joints > Wrist, hand and finger problems > Other wrist, hand and finger problems",
    "Muscles, bones and joints > Back problems",
    "Muscles, bones and joints > Elbow problems",
    "Muscles, bones and joints > Scoliosis",
    "Offenders and family support > Offender or ex - offender > Falsely accused",
    "Offenders and family support > Offender or ex - offender > Offender or ex - offender help",
    "Offenders and family support > Support for families",
    "Other health > Stutter and stammers",
    "Pain > Chronic pain",
    "Pain > Peripheral neuropathy(nerve pain)",
    "Pain > Post surgical pain(acute pain)",
    "Pain > Complex regional pain syndrome(CRPS)",
    "Pet bereavement > Pet bereavement and children",
    "Pet bereavement > Pet bereavement support",
    "Pet bereavement > Pet burial and cremation",
    "Pet bereavement > What to do if your pet dies",
    "Pet care > Find help to look after your pet",
    "Pet care > Pet care advice: cats",
    "Pet care > Pet care advice: dogs",
    "Pet care > Pet insurance",
    "Pet care > Pet care advice(general)",
    "Pet housing and ownership > Pet gets ill or dies after buying",
    "Pet housing and ownership > Pet ownership when separating",
    "Pet housing and ownership > Pets in rented properties",
    "Physical disabilities > Blind or visual impairments",
    "Physical disabilities > Cerebral palsy",
    "Physical disabilities > Deafblindness",
    "Physical disabilities > Deafness",
    "Physical disabilities > Limb loss",
    "Physical disabilities > Tourette's syndrome",
    "Physical disabilities > Physical disability support(general)",
    "Physical disabilities > Disability aids",
    "Police services > Police complaints",
    "Police services > Stop and search rights",
    "Preparing for your passing > End of life care > Advance statements and decisions(end of life)",
    "Preparing for your passing > End of life care > Deciding where to pass",
    "Preparing for your passing > End of life care > Find a hospice",
    "Preparing for your passing > Discussing last wishes",
    "Preparing for your passing > Donating your body or organs",
    "Preparing for your passing > End of life support for older adults",
    "Preparing for your passing > Funeral planning",
    "Preparing for your passing > Telling others you are dying",
    "Preparing for your passing > Leaving memories and messages",
    "Preparing for your passing > Making a will",
    "Preparing for your passing > Pet arrangements",
    "Preparing for your passing > Terminal diagnosis support",
    "Preparing for your passing > End of life planning(general)",
    "Preparing to lose a loved one > Being with someone when they die",
    "Preparing to lose a loved one > Coping with losing someone soon",
    "Problems at work > Support for workers > Agriculture, Horticulture and Animal Care",
    "Problems at work > Support for workers > Arts, Media and Publishing",
    "Problems at work > Support for workers > Business, Administration and Law",
    "Problems at work > Support for workers > Construction sector support",
    "Problems at work > Support for workers > Education and Training sector support",
    "Problems at work > Support for workers > Engineering and Manufacturing Technologies",
    "Problems at work > Support for workers > Health, Public and Care sector support",
    "Problems at work > Support for workers > Information and Communication Technology",
    "Problems at work > Support for workers > Leisure, Travel and Tourism",
    "Problems at work > Support for workers > Retail and Commercial Enterprise",
    "Problems at work > Support for workers > Science and Mathematics",
    "Problems at work > Support for workers > Zero hours",
    "Problems at work > Dealing with a disciplinary",
    "Problems at work > Workplace discrimination",
    "Problems at work > Dismissals",
    "Problems at work > Employment tribunals",
    "Problems at work > Help if you become ill or disabled",
    "Problems at work > How to raise a problem at work",
    "Problems at work > Stress at work",
    "Problems at work > Taking time off for caring",
    "Problems at work > Workplace bullying",
    "Problems at work > Forced to resign(constructive dismissal)",
    "Rare genetic disorders > Alstrom Syndrome",
    "Rare genetic disorders > X linked hypophosphatemia(XLH)",
    "Rare genetic disorders > Genetic leukodystrophy",
    "Rare genetic disorders > Mitochondrial disease",
    "Rare genetic disorders > Batten disease",
    "Rare genetic disorders > Alkaptonuria(AKU)",
    "Rare genetic disorders > Ehlers - danlos syndrom(EDS)",
    "Rare genetic disorders > Angelman syndrome",
    "Rare genetic disorders > Niemann - Pick disease",
    "Rare genetic disorders > Charcot Marie Tooth(CMT)",
    "Rare genetic disorders > Primary immunodeficiencies",
    "Rare genetic disorders > Mucopolysaccharidosis(MPS)",
    "Rare genetic disorders > Haemochromatosis",
    "Rare genetic disorders > Barth syndrome",
    "Rare genetic disorders > Gaucher disease",
    "Rare genetic disorders > Rare diseases(general)",
    "Rare genetic disorders > Rett syndrome",
    "Rare genetic disorders > PSP and CBD",
    "Rare genetic disorders > Sarcoidosis",
    "Rare genetic disorders > Schwannomatosis",
    "Rare genetic disorders > Neurofibromatosis",
    "Rare genetic disorders > Tracheo - oesophageal fistula(TOF)",
    "Rare genetic disorders > Encephalitis",
    "Rare genetic disorders > Rare parathyroid conditions",
    "Rare genetic disorders > Pituitary gland conditions",
    "Rare genetic disorders > Congenital diaphragmatic hernia",
    "Relationship support > Affairs and infidelity",
    "Relationship support > Problems communicating in couples",
    "Relationship support > Long - distance relationships",
    "Relationship support > Open relationships",
    "Relationship support > Relationship counselling",
    "Relationship support > Relationship doubts",
    "Renting and landlord issues > Find a rental > Affordable housing",
    "Renting and landlord issues > Find a rental > Find a house share",
    "Renting and landlord issues > Find a rental > Find a rental property",
    "Renting and landlord issues > Find a rental > Find a short term rental",
    "Renting and landlord issues > Find a rental > Find student accommodation",
    "Renting and landlord issues > Find a rental > Help to rent schemes",
    "Renting and landlord issues > Find a rental > Rental scams",
    "Renting and landlord issues > Housing complaints > Letting agent complaints",
    "Renting and landlord issues > Housing complaints > Landlord complaints",
    "Renting and landlord issues > Problems renting > Ending a joint tenancy",
    "Renting and landlord issues > Problems renting > Guarantors for private renters",
    "Renting and landlord issues > Problems renting > Landlord disputes",
    "Renting and landlord issues > Problems renting > Pest problems",
    "Renting and landlord issues > Problems renting > Renting with poor credit history",
    "Renting and landlord issues > Problems renting > Tenant disputes",
    "Renting and landlord issues > Renting rights > Landlord responsibilities",
    "Renting and landlord issues > Renting rights > Tenant responsibilities",
    "Renting and landlord issues > Renting for the first time",
    "Renting and landlord issues > Renting with pets",
    "Renting and landlord issues > Ending a tenancy early",
    "Renting and landlord issues > How to end a tenancy",
    "Renting and landlord issues > Problems getting the deposit back",
    "Repairs and adaptations > Repairs in rentals > Landlord fails to carry out repairs",
    "Repairs and adaptations > Repairs in rentals > Responsibilities for repairs",
    "Repairs and adaptations > Help with repair or adaptation costs",
    "Repairs and adaptations > Find a trader",
    "Repossessions and evictions > Help if you're facing repossession",
    "Repossessions and evictions > Illegal eviction / landlord harassment",
    "Repossessions and evictions > Renters facing eviction",
    "Repossessions and evictions > Sheriff officer powers",
    "Repossessions and evictions > Council or social housing evictions",
    "Sex and intimacy > Confidence in bed",
    "Sex and intimacy > Feeling pressured into sex",
    "Sex and intimacy > Intimacy issues",
    "Sex and intimacy > Reduced sex drive",
    "Sex and intimacy > Safe sex and sex education",
    "Sex and intimacy > Sex therapy",
    "Sex and intimacy > Talking about sex issues",
    "Sexual and reproductive health > Contraception and birth control > Contraception for men",
    "Sexual and reproductive health > Contraception and birth control > Contraception for women",
    "Sexual and reproductive health > Fertility > Coping with infertility",
    "Sexual and reproductive health > Fertility > Getting pregnant",
    "Sexual and reproductive health > Fertility > Fertility testing",
    "Sexual and reproductive health > Pregnancy health > Anaemia in pregnancy",
    "Sexual and reproductive health > Pregnancy health > Backache in pregnancy",
    "Sexual and reproductive health > Pregnancy health > Diabetes and pregnancy",
    "Sexual and reproductive health > Pregnancy health > Pelvic girdle pain in pregnancy",
    "Sexual and reproductive health > Pregnancy health > Pre - eclampsia in pregnancy",
    "Sexual and reproductive health > Pregnancy health > Morning sickness",
    "Sexual and reproductive health > Pregnancy health > Reducing the risk of stillbirth",
    "Sexual and reproductive health > Pregnancy health > Pregnancy scans",
    "Sexual and reproductive health > Pregnancy health > Antiphospholipid syndrome APS",
    "Sexual and reproductive health > STI's: Sexually Transmitted Infections  >  Chlamydia",
    "Sexual and reproductive health > STI's: Sexually Transmitted Infections  >  Genital warts",
    "Sexual and reproductive health > STI's: Sexually Transmitted Infections  >  Gonorrhoea",
    "Sexual and reproductive health > STI's: Sexually Transmitted Infections  >  Other STI's",
    "Sexual and reproductive health > STI's: Sexually Transmitted Infections  >  STI testing",
    "Sexual and reproductive health > STI's: Sexually Transmitted Infections  >  Syphilis",
    "Sexual and reproductive health > STI's: Sexually Transmitted Infections  >  Trichomonas",
    "Sexual and reproductive health > STI's: Sexually Transmitted Infections  >  Genital herpes",
    "Sexual and reproductive health > Sexual health and HIV",
    "Sexual and reproductive health > Sexual health resources",
    "Sexual and reproductive health > Abortion",
    "Sexual and reproductive health > Fertility treatments",
    "Sexual and reproductive health > Egg donors",
    "Skin, hair and nails > Acne and spots > Acne",
    "Skin, hair and nails > Acne and spots > Spots",
    "Skin, hair and nails > Birthmarks and scars > Birthmarks",
    "Skin, hair and nails > Birthmarks and scars > Scars",
    "Skin, hair and nails > Common skin conditions > Cold sores",
    "Skin, hair and nails > Common skin conditions > Impetigo",
    "Skin, hair and nails > Common skin conditions > Psoriasis",
    "Skin, hair and nails > Common skin conditions > Scabies",
    "Skin, hair and nails > Common skin conditions > Urticaria(hives)",
    "Skin, hair and nails > Common skin conditions > Vitiligo",
    "Skin, hair and nails > Common skin conditions > Warts and verrucas",
    "Skin, hair and nails > Eczema and dermatitis > Atopic eczema",
    "Skin, hair and nails > Eczema and dermatitis > Chronic actinic dermatitis",
    "Skin, hair and nails > Eczema and dermatitis > Dermatitis herpetiformis(DH)",
    "Skin, hair and nails > Eczema and dermatitis > Discoid eczema",
    "Skin, hair and nails > Eczema and dermatitis > Eczema",
    "Skin, hair and nails > Eczema and dermatitis > Seborrhoeic dermatitis",
    "Skin, hair and nails > Rashes > Lichen planus",
    "Skin, hair and nails > Rashes > Rashes in adults",
    "Skin, hair and nails > Rashes > Rashes in children",
    "Skin, hair and nails > Skin conditions > Achyonychia congenita",
    "Skin, hair and nails > Skin conditions > Ectodermal dysplasia",
    "Skin, hair and nails > Skin conditions > Epidermolysis Bullosa Simplex(EB)",
    "Skin, hair and nails > Skin conditions > Excessive sweating(hyperhidrosis)",
    "Skin, hair and nails > Skin conditions > Hereditary angioedema",
    "Skin, hair and nails > Skin conditions > Ichthyosis",
    "Skin, hair and nails > Skin conditions > Palmoplantar keratoderma",
    "Skin, hair and nails > Skin conditions > Rosacea",
    "Skin, hair and nails > Skin conditions > Scleroderma(systemic sclerosis)",
    "Skin, hair and nails > Skin conditions > Venous leg ulcers",
    "Skin, hair and nails > Skin conditions > Skin conditions(general)",
    "Skin, hair and nails > Skin growths and lesions > Actinic Keratosis",
    "Skin, hair and nails > Skin growths and lesions > Moles",
    "Skin, hair and nails > Skin growths and lesions > Seborrhoeic keratoses",
    "Skin, hair and nails > Skin growths and lesions > Skin tags",
    "Skin, hair and nails > Skin infections > Athlete's Foot",
    "Skin, hair and nails > Skin infections > Candida(yeast or thrush)",
    "Skin, hair and nails > Skin infections > Cellulitis",
    "Skin, hair and nails > Skin infections > Ringworm",
    "Skin, hair and nails > Skin infections > Shingles",
    "Skin, hair and nails > Alopecia",
    "Skin, hair and nails > Cleft lip and palate",
    "Skin, hair and nails > Nail conditions",
    "Sleep problems > Insomnia",
    "Sleep problems > Nightmares",
    "Sleep problems > Obstructive sleep apnoea(OSA)",
    "Sleep problems > Snoring",
    "Sleep problems > Trouble sleeping",
    "Sleep problems > Narcolepsy",
    "Social and council housing > Applying for social housing",
    "Social and council housing > Council housing complaint",
    "Social and council housing > Housing association complaint",
    "Social and council housing > Council housing advice",
    "Social and council housing > Stay in council home after a death",
    "Spiritual wellbeing > Buddhism support",
    "Spiritual wellbeing > Christianity support",
    "Spiritual wellbeing > Hinduism support",
    "Spiritual wellbeing > Islam support",
    "Spiritual wellbeing > Judaism support",
    "Spiritual wellbeing > Sikhism support",
    "Starting a family > Becoming adoptive parents > Adoption agencies",
    "Starting a family > Becoming adoptive parents > How to adopt",
    "Starting a family > Becoming adoptive parents > Support for adoptive parents",
    "Starting a family > Becoming adoptive parents > Thinking about adopting",
    "Starting a family > Becoming foster parents > Becoming a foster parent",
    "Starting a family > Becoming foster parents > Fostering agencies",
    "Starting a family > Becoming foster parents > Support for foster parents",
    "Starting a family > Becoming foster parents > Thinking about fostering",
    "Starting a family > Birth options and support > Birth options",
    "Starting a family > Birth options and support > Find a Doula",
    "Starting a family > Birth options and support > Private midwives",
    "Starting a family > Family planning > Family planning resources",
    "Starting a family > Family planning > Getting pregnant tips",
    "Starting a family > Pregnancy wellbeing > Exercising when pregnant",
    "Starting a family > Pregnancy wellbeing > Feelings when pregnant",
    "Starting a family > Pregnancy wellbeing > Healthy eating when pregnant",
    "Starting a family > Pregnancy wellbeing > Postpartum(after birth) care",
    "Starting a family > Pregnancy wellbeing > Relationships and pregnancy",
    "Starting a family > Pregnancy wellbeing > Sleep and tiredness when pregnant",
    "Starting a family > Pregnancy wellbeing > Pregnancy wellbeing resources(general)",
    "Starting a family > Surrogacy support > Being a surrogate for a friend",
    "Starting a family > Surrogacy support > Support for surrogate parents",
    "Starting a family > Surrogacy support > Support for surrogates",
    "Starting a family > Surrogacy support > Surrogacy agencies",
    "Storms and flooding > Prepare for floods or storms",
    "Storms and flooding > Support after a flood or storm",
    "Student money > Student finance options",
    "Student money > Student debt support",
    "Support for grandparents > Estranged grandparents",
    "Support for grandparents > Raising grandchildren",
    "Support for parents > Co - parenting support",
    "Support for parents > Having twins, triplets or more",
    "Support for parents > Parents on low incomes",
    "Support for parents > Same - sex parents",
    "Support for parents > Single parents",
    "Support for parents > Step - parents",
    "Support for parents > Support for new dads",
    "Support for parents > Support for new mums",
    "Support for parents > Parenting advice",
    "Support for parents > Young parents",
    "Support for students > Free online learning",
    "Support for students > Help applying for a course",
    "Support for students > Help for ill or disabled students",
    "Support for students > Help selecting a course",
    "Support for students > Student mental health",
    "Support for students > Student work experience",
    "Support in Court > Extra help at court",
    "Support in Court > Giving evidence",
    "Support in Court > Understanding court processes",
    "Travel health > If you get ill abroad",
    "Travel health > Stay safe in the sun",
    "Travel health > Vaccinations",
    "Urinary and bladder > Chronic kidney disease",
    "Urinary and bladder > Kidney infection(pyelonephritis)",
    "Urinary and bladder > Kidney stones(or calculi)",
    "Urinary and bladder > Microalbuminuria",
    "Urinary and bladder > Urinary incontinence",
    "Urinary and bladder > Urinary tract infections",
    "Vets and vet advice > Complain about your vet",
    "Vets and vet advice > Find a vet",
    "Vets and vet advice > Free vet care or help with fees",
    "Victim support > Challenge CPS or parole decisions",
    "Victim support > Help to feel safe after crime",
    "Victim support > Support for victim families",
    "Victim support > Compensation and financial aid",
    "Victim support > Dealing with the media",
    "Victim support > Victim support organisations",
    "Victim support > Support for young victims",
    "Victim support > Victims' rights",
    "Viruses and infections > Lyme disease, Malaria, Yellow Fever > Lyme disease",
    "Viruses and infections > Lyme disease, Malaria, Yellow Fever > Malaria",
    "Viruses and infections > Lyme disease, Malaria, Yellow Fever > Yellow fever",
    "Viruses and infections > Coronavirus(covid - 19) > Advice and information",
    "Viruses and infections > Coronavirus(covid - 19) > Coronavirus anxiety",
    "Viruses and infections > Coronavirus(covid - 19) > Survivor support(long covid)",
    "Viruses and infections > Coronavirus(covid - 19) > Isolating or shielding support",
    "Viruses and infections > Hepatitis > Hepatitis A",
    "Viruses and infections > Hepatitis > Hepatitis B",
    "Viruses and infections > Hepatitis > Hepatitis C",
    "Viruses and infections > Hepatitis > Hepatitis D",
    "Viruses and infections > HIV and AIDS > AIDS",
    "Viruses and infections > HIV and AIDS > HIV",
    "Viruses and infections > Poisoning > E coli",
    "Viruses and infections > Poisoning > Food poisoning",
    "Viruses and infections > Poisoning > Lead poisoning",
    "Viruses and infections > Measles",
    "Viruses and infections > Post - polio syndrome",
    "Viruses and infections > Tetanus(lockjaw)",
    "Viruses and infections > Tuberculosis(TB)",
    "Viruses and infections > Zika virus",
    "Viruses and infections > Loss of taste or smell",
    "Witness support > Witness safety support",
    "Witness support > Witness support organisations",
    "Women's health > Pelvic health  >  Pelvic inflammatory disease (PID)",
    "Women's health > Pelvic health  >  Pelvic organ prolapse",
    "Women's health > Pelvic health  >  Vaginal mesh issues",
    "Women's health > Period health  >  Periods",
    "Women's health > Period health  >  Premenstrual dysphoric disorder (PMDD)",
    "Women's health > Period health  >  Premenstrual Syndrome (PMS)",
    "Women's health > Period health  >  Toxic Shock Syndrome (TSS)",
    "Women's health  >  Endometriosis",
    "Women's health  >  Fibroids",
    "Women's health  >  Hormones",
    "Women's health  >  Hysterectomy",
    "Women's health  >  Lipoedema",
    "Women's health  >  Menopause health",
    "Women's health  >  Polycystic Ovary Syndrome (PCOS)",
    "Women's health  >  Turner's syndrome",
    "Women's health  >  Hormone Replacement Therapy (HRT)",
    "Work and disabled people > Help looking for work",
    "Work and disabled people > Interview advice",
    "Work and disabled people > Interview support for the disabled",
    "Work and disabled people > Support in work",
    "Work money matters > Are you being paid enough ?",
    "    Work money matters > Maternity and paternity pay",
    "Work money matters > Negotiating your salary",
    "Work money matters > Pensions",
    "Work money matters > Self - employed support",
    "Work money matters > Sick pay",
    "Work money matters > Small business owner support",
    "Work money matters > Withheld wages",
    "Your child's development > Parent support (0-12 months)  >  Communication (0-12months)",
    "Your child's development > Parent support (0-12 months)  >  Crying and colic (0-12months)",
    "Your child's development > Parent support (0-12 months)  >  Emotional wellbeing (0-12months)",
    "Your child's development > Parent support (0-12 months)  >  Exercises and activities (0-12months)",
    "Your child's development > Parent support (0-12 months)  >  Learning support (0-12months)",
    "Your child's development > Parent support (0-12 months)  >  Nutrition and weaning (0-12months)",
    "Your child's development > Parent support (0-12 months)  >  Parent resources (0-12months)",
    "Your child's development > Parent support (0-12 months)  >  Safety (0-12months)",
    "Your child's development > Parent support (0-12 months)  >  Sleep support (0-12months)",
    "Your child's development > Parent support (0-12 months)  >  Breast feeding",
    "Your child's development > Parent support (2-5 years)  >  Activities (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Behavioural support (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Communication skills (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Emotional wellbeing (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Fitness and exercise (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Learning support (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Life skills (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Healthy eating (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Parent resources (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Safety (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Sleep support (2- 5 years)",
    "Your child's development > Parent support (2-5 years)  >  Social skills and confidence (2- 5 years)",
    "Your child's development > Parent support (5-12 years)  >  Activities (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Behavioural support (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Communication skills (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Emotional wellbeing (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Fitness and exercise (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Learning support (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Life skills (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Healthy eating (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Parent resources (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Safety (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Sleep support (5 -12 years)",
    "Your child's development > Parent support (5-12 years)  >  Social skills and confidence (5 -12 years)",
    "Your child's development > Parent support (13-18years)  >  Behavioural support (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Communication skills (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Emotional wellbeing (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Explore career and study options (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Fitness and exercise (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Life skills (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Parent resources (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Safety (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  School problems (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Sleep support (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Social skills and confidence (13-18 years)",
    "Your child's development > Parent support (13-18years)  >  Activities (13-18 years)",
    "Your child's development > Parent support (12months-2years)  >  Behavioural support (12months - 2 years)",
    "Your child's development > Parent support (12months-2years)  >  Communication skills (12months - 2 years)",
    "Your child's development > Parent support (12months-2years)  >  Emotional wellbeing (12months - 2 years)",
    "Your child's development > Parent support (12months-2years)  >  Exercises and activities (12months - 2 years)",
    "Your child's development > Parent support (12months-2years)  >  Learning support (12months - 2 years)",
    "Your child's development > Parent support (12months-2years)  >  Healthy eating (12months - 2 years)",
    "Your child's development > Parent support (12months-2years)  >  Parent resources (12months - 2 years)",
    "Your child's development > Parent support (12months-2years)  >  Potty training",
    "Your child's development > Parent support (12months-2years)  >  Safety (12months - 2 years)",
    "Your child's development > Parent support (12months-2years)  >  Sleep support (12months - 2 years)",
    "Your rights at work > Being monitored at work",
    "Your rights at work > Discrimination at work",
    "Your rights at work > Employment law support",
    "Your rights at work > Help to understand your rights",
    "Your rights at work > Industrial actions and strikes",
    "Your rights at work > Industrial actions and strikes",
    "Your rights at work > Reasonable adjustments if disabled or ill",
    "Your rights at work > Trade unions",
    "Your rights at work > Workplace health and safety"
]